config/routes.rb
Rails.application.routes.draw do
   root to: 'posts#index'
   get '/posts' => 'posts#index'
   get '/:short_url' => 'posts#redirect'
   post '/send_sms' => 'posts#send_sms'

   resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @post =  Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.find_by(short_url: params[:short_url])
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create

    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Nice! Here is your shortlink:'}
        #format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        #format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Link updated!' }
        #format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        #format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Link deleted!' }
      #format.json { head :no_content }
    end
  end

  def send_sms
   message = params[:message]
   number = params[:number]
   account_sid = 'AC1547d925a49e6c23d7b221223d78633a'
   auth_token = 'fabc6dc88501f5e00975d2d036646bd7'
   @client = Twilio::REST::Client.new account_sid, auth_token

   @message = @client.account.messages.create({
     :to => "+1"+"#{number}",
     :from => "+18572142112",
     :body => "Hi, check out this awesome website: https://shortlinksms.herokuapp.com/#{message}"
     })

     respond_to do |format|
       format.html { redirect_to :back, notice: 'Message Sent!' }
     end
   #end
  end #end of def send_sms

  # Use callbacks to share common setup or constraints between actions.
  def set_post
      @post = Post.find(params[:id])
  end

  def redirect
    @post = Post.find_by(short_url: params[:short_url])
    redirect_to @post.url
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:id, :url, :short_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShortlinkSmsApp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=0.8, maximum-scale=0.8">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1 class="ui center aligned header">Short Link SMS Application</h1>
    <%= yield %>
    <a href="https://github.com/dorianpenaloza/shortlink_sms_app" target="_blank">
      <h3 class="ui center aligned header"><i class="github icon"></i>View repository on Github</h3>
    </a>

  </body>
</html>

app/views/posts/_form.html.erb
<div class="ui segments">
  <div class="ui green inverted segment">
    <h3><i class="magic icon"></i>Generate Short Link</h3>
  </div>
  <div class="ui segment">
    <%= form_for @post do |f| %>
    <div class="field">
      <%= f.label :url, "Copy and paste your very long URL here:" %>
      <%= f.text_field :url, :class => "ui input segments new_input", :placeholder => "e.g. https://verylongurl.com", :required => 'true', :type => "url" %>
      <%= f.text_field :short_url, :class => "ui input segments", :placeholder => "custom name", :required => 'true' %>
    </div>
    <div class="actions">
    <%= f.submit 'Submit', :class => "ui green button" %>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/_form_sms.html.erb
<h3><i class="external share icon"></i> Share this link with a friend</h3>
  <%= form_tag('/send_sms', method: 'POST') do %>
  <input id="input_phone" type="tel" placeholder="xxxxxxxxxx" name="number" class="ui input segments" title="No Spaces: XXXXXXXXXX" pattern="^\d{3}\d{3}\d{4}$" required>
  <input type="hidden" value="<%= @post.short_url %>" name="message">
  <button type="submit" class="ui green button"><i class="send icon"></i> Send Text</button>
  <% end %>

app/views/posts/edit.html.erb
<h3 id="notice " class="ui center aligned header"><%= notice %></h3>

<div class="ui blue inverted segment">
  <div class="ui segment stackable two column grid">
    <div class="column ui divided selection list">

        <%= form_for(@post) do |f| %>
          <div class="">
            <div class="ui red horizontal label">Long URL</div>
            <%= f.text_field :url, :class => "ui input segments new_input", :placeholder => "e.g. https://verylongurl.com", :required => 'true', :type => "url" %><br>
            <div class="ui blue horizontal label">Short URL</div>
            <%= f.text_field :short_url, :class => "ui input segments", :placeholder => "custom name", :required => 'true' %>
          </div>
    </div>
  </div>

        <div class="ui buttons">
          <%= link_to 'Back', @post, :class => "ui button" %>
          <div class="or"></div>
          <%= f.submit 'Update', :class => "ui green button" %>
          <div class="or"></div>
          <%= link_to 'Delete', @post, :class => "ui red button", method: :delete, data: { confirm: 'Wait! Are you sure?' } %>
          <% end %>
        </div>

      <%= render "form_sms" %>

</div>

app/views/posts/index.html.erb
<h3 id="notice" class="ui center aligned header"><%= notice %></h3>
<div class="ui blue inverted segment">

<span id="form"> <%= render 'form' %> </span>

  <% @posts.each do |post| %>
    <div class="ui segment stackable two column grid">
      <div class="column ui divided selection list">
        <a class="item" target="_blank" href="<%= post.url %>">
          <div class="ui red horizontal label">Long URL</div>
          <%= post.url %>
        </a>
        <a class="item" target="_blank" href="<%= post.short_url %>">
          <div class="ui blue horizontal label">Short URL</div>
          https://<%= request.host %>/<%= post.short_url %>
        </a>
      </div>
      <div class="column float right">
      <%= button_to 'Show', post, :class => "ui green basic button", :method => :get %>
      <%= button_to 'Edit', edit_post_path(post), :class => "ui blue basic button", :method => :get %>
      <%= button_to 'Delete', post, :class => "ui red basic button ", method: :delete, data: { confirm: 'Wait! Are you sure?' } %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h3 id="notice" class="ui center aligned header"><%= notice %></h3>

<div class="ui blue inverted segment">

  <div class="ui segment stackable two column grid">
    <div class="column ui divided selection list">
      <a class="item" target="_blank" href="<%= @post.url %>">
        <div class="ui red horizontal label">Long URL</div>
        <%= @post.url %>
      </a>

      <a class="item" target="_blank" href="<%= @post.url %>">
        <div class="ui blue horizontal label">Short URL</div>
          https://<%= request.host %>/<%= @post.short_url %>
      </a>
    </div>
  </div>

<div class="ui buttons">
  <%= link_to 'Back', posts_path, :class => "ui button" %>
  <div class="or"></div>
  <%= link_to 'Edit', edit_post_path(@post), :class => "ui green button", :method => :get %>
  <div class="or"></div>
  <%= link_to 'Delete', @post, :class => "ui red button", method: :delete, data: { confirm: 'Wait! Are you sure?' } %>
</div>

<%= render "form_sms" %>

</div>